#Task2: Try Linear regression on same prediction data using Tensorflow

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.05941016, 0.21421521],
       [0.42196142, 0.3371672 ],
       [0.25314963, 0.52750079]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([-0.49750594,  1.15037299])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[42.99628454 62.06081959]
 [58.24299936 84.07472112]
 [75.8966862  95.56254699]
 [33.07320725 57.01604296]
 [61.83056506 85.22432892]
 [42.99628454 62.06081959]
 [58.24299936 84.07472112]
 [75.8966862  95.56254699]
 [33.07320725 57.01604296]
 [61.83056506 85.22432892]
 [42.99628454 62.06081959]
 [58.24299936 84.07472112]
 [75.8966862  95.56254699]
 [33.07320725 57.01604296]
 [61.83056506 85.22432892]], shape=(15, 2), dtype=float64)


In [7]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(765.4908117910165, shape=(), dtype=float64)


In [8]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 765.4908117910165
 
 Epoch count: 1 
 Loss value: 558.427191518326
 
 Epoch count: 2 
 Loss value: 419.50852342418597
 
 Epoch count: 3 
 Loss value: 324.36518711807156
 
 Epoch count: 4 
 Loss value: 257.6114237527858
 
 Epoch count: 5 
 Loss value: 209.49894023431645
 
 Epoch count: 6 
 Loss value: 173.82130790886896
 
 Epoch count: 7 
 Loss value: 146.601112014972
 
 Epoch count: 8 
 Loss value: 125.26701389396882
 
 Epoch count: 9 
 Loss value: 108.13749983087231
 
 Epoch count: 10 
 Loss value: 94.09666656425678
 
 Epoch count: 11 
 Loss value: 82.39029747506466
 
 Epoch count: 12 
 Loss value: 72.49732664548013
 
 Epoch count: 13 
 Loss value: 64.04858327214428
 
 Epoch count: 14 
 Loss value: 56.775218009697
 
 Epoch count: 15 
 Loss value: 50.47578904176452
 
 Epoch count: 16 
 Loss value: 44.99510129179593
 
 Epoch count: 17 
 Loss value: 40.210468265248785
 
 Epoch count: 18 
 Loss value: 36.0226787983956
 
 Epoch count: 19 
 Loss value: 32.349